import { makeStyles, shorthands } from "@griffel/react";
import {
  colors,
  gradients,
  semanticColors,
  warm,
} from "../../../common/theme/colors";
import {
  layout,
  typography,
  typographyPresets,
} from "../../../common/theme/typography";

export const useRecommendationsStyles = makeStyles({
  page: {
    position: "relative",
    fontFamily: typography.fontFamily.sans,
    backgroundColor: semanticColors.bgPage,
    minHeight: "100dvh",
    // Wallpaper lives on a fixed pseudo-element instead of
    // background-attachment: fixed on the page itself - that property forces
    // the browser to repaint the background on every scroll frame, which is
    // what caused the scroll jank. A position: fixed layer gets its own
    // compositor layer, so scrolling the content above it is cheap, while
    // still sizing "cover" against the viewport rather than the full
    // scroll height.
    "::before": {
      content: "\"\"",
      position: "fixed",
      inset: 0,
      zIndex: -1,
      backgroundImage: warm.bgImage,
      backgroundSize: "cover",
      backgroundPosition: "top center",
      backgroundRepeat: "no-repeat",
    },
  },
  content: {
    width: "100%",
    boxSizing: "border-box",
    maxWidth: "1240px",
    marginLeft: "auto",
    marginRight: "auto",
    padding: `150px ${layout.padding.xl} ${layout.padding["2xl"]}`,
    display: "flex",
    flexDirection: "column",
    rowGap: layout.gap.lg,
    "@media (max-width: 720px)": {
      padding: `128px ${layout.padding.md} ${layout.padding.xl}`,
    },
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: layout.gap.md,
    flexWrap: "wrap",
    minWidth: 0,
  },
  title: {
    margin: 0,
    ...typographyPresets.h2,
    color: semanticColors.textPrimary,
  },
  subtitle: {
    margin: `${layout.gap.xs} 0 0`,
    fontSize: typography.fontSize.size4,
    color: semanticColors.textSecondary,
  },
  countBadge: {
    color: semanticColors.textSecondary,
    backgroundColor: semanticColors.bgPrimary,
    ...shorthands.border(
      layout.borderWidth.thin,
      "solid",
      semanticColors.borderDefault,
    ),
    ...shorthands.borderRadius(layout.radius.md),
    ...shorthands.padding(layout.spacing[2.5], "14px"),
    fontSize: typography.fontSize.size3,
    fontWeight: typography.fontWeight.medium,
    lineHeight: typography.lineHeight.normal,
  },
  filtersPanel: {
    backgroundColor: semanticColors.bgPrimary,
    ...shorthands.border(
      layout.borderWidth.thin,
      "solid",
      semanticColors.borderDefault,
    ),
    ...shorthands.borderRadius(layout.radius.xl),
    padding: layout.padding.lg,
    display: "flex",
    alignItems: "center",
    gap: layout.gap.md,
    flexWrap: "wrap",
    boxShadow: semanticColors.shadowStrong,
    minWidth: 0,
  },
  categoryTabs: {
    display: "flex",
    gap: layout.gap.xs,
    flexWrap: "wrap",
    minWidth: 0,
  },
  categoryTab: {
    ...shorthands.padding(layout.spacing[2], "14px"),
    ...shorthands.borderRadius(layout.radius.full),
    ...shorthands.border(
      layout.borderWidth.thin,
      "solid",
      semanticColors.borderDefault,
    ),
    backgroundColor: semanticColors.bgPrimary,
    color: semanticColors.textTertiary,
    fontSize: typography.fontSize.size3,
    fontWeight: typography.fontWeight.semibold,
    cursor: "pointer",
    transitionProperty: "background-color, border-color, color, transform",
    transitionDuration: layout.duration.normal,
    ":hover": {
      ...shorthands.borderColor(semanticColors.borderAccent),
      color: semanticColors.interactive,
      transform: "translateY(-1px)",
    },
  },
  categoryTabActive: {
    ...shorthands.borderColor(colors.transparent),
    backgroundImage: gradients.primary,
    color: semanticColors.bgPrimary,
  },
  divider: {
    width: "1px",
    height: layout.spacing[7],
    backgroundColor: semanticColors.borderDefault,
    "@media (max-width: 560px)": {
      display: "none",
    },
  },
  budgetSelect: {
    width: "170px",
    maxWidth: "100%",
    height: layout.controlSize.lg,
    ...shorthands.borderRadius(layout.radius.md),
    ...shorthands.border(
      layout.borderWidth.thin,
      "solid",
      semanticColors.borderDefault,
    ),
    ...shorthands.padding("0", "12px"),
    color: semanticColors.textTertiary,
    backgroundColor: semanticColors.bgPrimary,
    fontSize: typography.fontSize.size3,
    fontWeight: typography.fontWeight.semibold,
    fontFamily: typography.fontFamily.sans,
    ":focus-visible": {
      outlineColor: semanticColors.interactive,
      outlineStyle: "solid",
      outlineWidth: layout.borderWidth.thick,
      outlineOffset: "2px",
    },
    // Native <option> elements don't inherit font styling from the <select>
    // in every browser, so restate it explicitly to keep the dropdown list
    // matching the trigger (and the category tabs it sits next to).
    "& option": {
      color: semanticColors.textPrimary,
      backgroundColor: semanticColors.bgPrimary,
      fontSize: typography.fontSize.size3,
      fontWeight: typography.fontWeight.semibold,
      fontFamily: typography.fontFamily.sans,
    },
  },
  ratingWrap: {
    display: "flex",
    alignItems: "center",
    gap: layout.gap.xs,
    flexWrap: "wrap",
  },
  ratingLabel: {
    fontSize: typography.fontSize.size3,
    color: semanticColors.textTertiary,
    fontWeight: typography.fontWeight.medium,
  },
  ratingButtons: {
    display: "flex",
    gap: layout.spacing[1.5],
    flexWrap: "wrap",
  },
  ratingButton: {
    ...shorthands.padding("5px", "10px"),
    ...shorthands.borderRadius(layout.radius.sm),
    ...shorthands.border(
      layout.borderWidth.thin,
      "solid",
      semanticColors.borderDefault,
    ),
    backgroundColor: semanticColors.bgPrimary,
    color: semanticColors.textTertiary,
    fontSize: typography.fontSize.size2,
    fontWeight: typography.fontWeight.semibold,
    cursor: "pointer",
  },
  ratingButtonActive: {
    ...shorthands.borderColor(colors.warning),
    backgroundColor: colors.warningTint,
    color: colors.warning,
  },
  grid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(min(300px, 100%), 1fr))",
    gap: layout.gap.md,
  },
  card: {
    display: "flex",
    flexDirection: "column",
    // The grid stretches every card in a row to match the tallest one -
    // filling that height and laying the card out as a column is what lets
    // the actions row anchor to the bottom instead of trailing right after
    // a short description.
    height: "100%",
    backgroundColor: semanticColors.bgPrimary,
    ...shorthands.border(
      layout.borderWidth.thin,
      "solid",
      semanticColors.borderDefault,
    ),
    ...shorthands.borderRadius(layout.radius.xl),
    overflow: "hidden",
    boxShadow: semanticColors.shadowLight,
    transitionProperty: "border-color, transform, box-shadow",
    transitionDuration: layout.duration.normal,
    ":hover": {
      ...shorthands.borderColor(semanticColors.borderAccent),
      transform: "translateY(-3px)",
      boxShadow: semanticColors.shadowMedium,
    },
  },
  imageWrap: {
    height: "180px",
    position: "relative",
    backgroundColor: semanticColors.bgTertiary,
  },
  image: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
    display: "block",
  },
  categoryPill: {
    position: "absolute",
    top: layout.spacing[3],
    left: layout.spacing[3],
    fontSize: typography.fontSize.size1,
    lineHeight: typography.lineHeight.normal,
    fontWeight: typography.fontWeight.bold,
    ...shorthands.padding(layout.spacing[1], "10px"),
    ...shorthands.borderRadius(layout.radius.full),
    backgroundColor: semanticColors.bgPrimary,
    color: semanticColors.textSecondary,
  },
  saveButton: {
    position: "absolute",
    top: layout.spacing[2.5],
    right: layout.spacing[3],
    width: layout.controlSize.xs,
    height: layout.controlSize.xs,
    ...shorthands.borderRadius(layout.radius.sm),
    ...shorthands.border(
      layout.borderWidth.hairline,
      "solid",
      semanticColors.borderLight,
    ),
    backgroundColor: semanticColors.surfaceTranslucent,
    color: semanticColors.textSecondary,
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: typography.fontSize.size6,
    transitionProperty: "transform",
    transitionDuration: layout.duration.normal,
    ":hover": {
      transform: "scale(1.05)",
    },
  },
  saveButtonActive: {
    color: semanticColors.interactive,
  },
  cardBody: {
    display: "flex",
    flexDirection: "column",
    flex: 1,
    padding: "16px 18px 18px",
  },
  titleRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: layout.gap.xs,
    marginBottom: layout.spacing[1.5],
  },
  cardTitle: {
    margin: 0,
    ...typographyPresets.h3,
    color: semanticColors.textPrimary,
    flex: 1,
    minWidth: 0,
    overflowWrap: "anywhere",
  },
  ratingMeta: {
    display: "flex",
    alignItems: "center",
    gap: layout.spacing[1],
    flexShrink: 0,
  },
  star: {
    color: colors.warning,
    fontSize: typography.fontSize.size3,
  },
  ratingValue: {
    fontSize: typography.fontSize.size3,
    color: semanticColors.textPrimary,
    fontWeight: typography.fontWeight.bold,
  },
  reviews: {
    fontSize: typography.fontSize.size2,
    color: semanticColors.textDisabled,
  },
  metaRow: {
    display: "flex",
    gap: layout.spacing[1.5],
    alignItems: "center",
    flexWrap: "wrap",
    marginBottom: layout.spacing[2.5],
  },
  location: {
    fontSize: typography.fontSize.size2,
    color: semanticColors.textTertiary,
  },
  price: {
    fontSize: typography.fontSize.size2,
    color: colors.success,
    fontWeight: typography.fontWeight.semibold,
  },
  description: {
    margin: "0 0 14px",
    fontSize: typography.fontSize.size3,
    color: semanticColors.textSecondary,
    lineHeight: "1.65",
  },
  tags: {
    display: "flex",
    gap: layout.spacing[1.5],
    flexWrap: "wrap",
    marginBottom: layout.spacing[3.5],
  },
  tag: {
    fontSize: typography.fontSize.size1,
    fontWeight: typography.fontWeight.semibold,
    ...shorthands.padding("3px", "8px"),
    ...shorthands.borderRadius(layout.radius.full),
    backgroundColor: semanticColors.bgInteractiveSubtle,
    color: semanticColors.interactive,
  },
  actions: {
    display: "flex",
    gap: layout.gap.xs,
    flexWrap: "wrap",
    marginTop: "auto",
    paddingTop: layout.spacing[3],
  },
  actionButton: {
    flex: 1,
    minWidth: "120px",
    height: layout.controlSize.md,
    ...shorthands.borderRadius(layout.radius.sm),
    fontSize: typography.fontSize.size2,
    fontWeight: typography.fontWeight.semibold,
    cursor: "pointer",
    fontFamily: typography.fontFamily.sans,
  },
  primaryButton: {
    backgroundImage: gradients.primary,
    color: semanticColors.bgPrimary,
    border: "none",
  },
  secondaryButton: {
    backgroundColor: semanticColors.bgPrimary,
    color: semanticColors.textSecondary,
    ...shorthands.border(
      layout.borderWidth.thin,
      "solid",
      semanticColors.borderDefault,
    ),
  },
  pagination: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: layout.gap.md,
    flexWrap: "wrap",
  },
  paginationStatus: {
    fontSize: typography.fontSize.size3,
    color: semanticColors.textSecondary,
    fontWeight: typography.fontWeight.medium,
  },
  paginationActions: {
    display: "flex",
    gap: layout.gap.xs,
    flexWrap: "wrap",
  },
  paginationButton: {
    minWidth: "96px",
    height: layout.controlSize.md,
    ...shorthands.borderRadius(layout.radius.sm),
    ...shorthands.border(
      layout.borderWidth.thin,
      "solid",
      semanticColors.borderDefault,
    ),
    backgroundColor: semanticColors.bgPrimary,
    color: semanticColors.textSecondary,
    fontSize: typography.fontSize.size2,
    fontWeight: typography.fontWeight.semibold,
    cursor: "pointer",
    fontFamily: typography.fontFamily.sans,
    ":hover": {
      ...shorthands.borderColor(semanticColors.borderAccent),
      color: semanticColors.interactive,
    },
    ":disabled": {
      color: semanticColors.textDisabled,
      cursor: "not-allowed",
      opacity: 0.7,
    },
  },
  emptyState: {
    textAlign: "center",
    ...shorthands.padding(layout.spacing[16], "40px"),
  },
  emptyIcon: {
    fontSize: typography.displaySize.xl,
    marginBottom: layout.spacing[4],
  },
  emptyTitle: {
    fontSize: typography.fontSize.size8,
    fontWeight: typography.fontWeight.bold,
    color: semanticColors.textPrimary,
    marginBottom: layout.spacing[2],
  },
  emptySubtitle: {
    fontSize: typography.fontSize.size4,
    color: semanticColors.textTertiary,
  },
});
