import { makeStyles, shorthands } from "@griffel/react";
import {
  colors,
  gradients,
  semanticColors,
} from "../../../common/theme/colors";
import {
  layout,
  typography,
  typographyPresets,
} from "../../../common/theme/typography";

export const useRecommendationsStyles = makeStyles({
  page: {
    fontFamily: typography.fontFamily.sans,
    backgroundColor: semanticColors.bgPage,
    minHeight: "100dvh",
  },
  content: {
    maxWidth: "1240px",
    marginLeft: "auto",
    marginRight: "auto",
    padding: `${layout.navHeight + 40}px ${layout.padding.xl} ${layout.padding["2xl"]}`,
    display: "flex",
    flexDirection: "column",
    rowGap: layout.gap.lg,
    "@media (max-width: 720px)": {
      padding: `${layout.navHeight + 30}px ${layout.padding.md} ${layout.padding.xl}`,
    },
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: layout.gap.md,
    flexWrap: "wrap",
  },
  title: {
    margin: 0,
    ...typographyPresets.h2,
    color: semanticColors.textPrimary,
  },
  subtitle: {
    margin: `${layout.gap.xs} 0 0`,
    fontSize: typography.fontSize.size4,
    color: semanticColors.textSecondary,
  },
  countBadge: {
    color: semanticColors.textSecondary,
    backgroundColor: semanticColors.bgPrimary,
    ...shorthands.border("1.5px", "solid", semanticColors.borderDefault),
    ...shorthands.borderRadius(layout.radius.md),
    ...shorthands.padding("10px", "14px"),
    fontSize: typography.fontSize.size3,
    fontWeight: typography.fontWeight.medium,
    lineHeight: typography.lineHeight.normal,
  },
  filtersPanel: {
    backgroundColor: semanticColors.bgPrimary,
    ...shorthands.border("1.5px", "solid", semanticColors.borderDefault),
    ...shorthands.borderRadius(layout.radius.xl),
    padding: layout.padding.lg,
    display: "flex",
    alignItems: "center",
    gap: layout.gap.md,
    flexWrap: "wrap",
    boxShadow: semanticColors.shadowStrong,
  },
  categoryTabs: {
    display: "flex",
    gap: layout.gap.xs,
    flexWrap: "wrap",
  },
  categoryTab: {
    ...shorthands.padding("8px", "14px"),
    ...shorthands.borderRadius(layout.radius.full),
    ...shorthands.border("1.5px", "solid", semanticColors.borderDefault),
    backgroundColor: semanticColors.bgPrimary,
    color: semanticColors.textTertiary,
    fontSize: typography.fontSize.size3,
    fontWeight: typography.fontWeight.semibold,
    cursor: "pointer",
    transitionProperty: "background-color, border-color, color, transform",
    transitionDuration: "0.2s",
    ":hover": {
      ...shorthands.borderColor(semanticColors.borderAccent),
      color: semanticColors.interactive,
      transform: "translateY(-1px)",
    },
  },
  categoryTabActive: {
    ...shorthands.borderColor(colors.transparent),
    backgroundImage: gradients.primary,
    color: semanticColors.bgPrimary,
  },
  divider: {
    width: "1px",
    height: "28px",
    backgroundColor: semanticColors.borderDefault,
  },
  budgetSelect: {
    width: "170px",
    height: "40px",
    ...shorthands.borderRadius(layout.radius.md),
    ...shorthands.border("1.5px", "solid", semanticColors.borderDefault),
    ...shorthands.padding("0", "12px"),
    color: semanticColors.textPrimary,
    backgroundColor: semanticColors.bgPrimary,
    fontSize: typography.fontSize.size3,
    fontFamily: typography.fontFamily.sans,
    ":focus-visible": {
      outlineColor: semanticColors.interactive,
      outlineStyle: "solid",
      outlineWidth: "2px",
      outlineOffset: "2px",
    },
  },
  ratingWrap: {
    display: "flex",
    alignItems: "center",
    gap: layout.gap.xs,
    flexWrap: "wrap",
  },
  ratingLabel: {
    fontSize: typography.fontSize.size3,
    color: semanticColors.textTertiary,
    fontWeight: typography.fontWeight.medium,
  },
  ratingButtons: {
    display: "flex",
    gap: "6px",
    flexWrap: "wrap",
  },
  ratingButton: {
    ...shorthands.padding("5px", "10px"),
    ...shorthands.borderRadius(layout.radius.sm),
    ...shorthands.border("1.5px", "solid", semanticColors.borderDefault),
    backgroundColor: semanticColors.bgPrimary,
    color: semanticColors.textTertiary,
    fontSize: typography.fontSize.size2,
    fontWeight: typography.fontWeight.semibold,
    cursor: "pointer",
  },
  ratingButtonActive: {
    ...shorthands.borderColor(colors.warning),
    backgroundColor: "rgba(245, 158, 11, 0.08)",
    color: colors.warning,
  },
  grid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(300px, 1fr))",
    gap: layout.gap.md,
  },
  card: {
    backgroundColor: semanticColors.bgPrimary,
    ...shorthands.border("1.5px", "solid", semanticColors.borderDefault),
    ...shorthands.borderRadius(layout.radius.xl),
    overflow: "hidden",
    boxShadow: semanticColors.shadowLight,
    transitionProperty: "border-color, transform, box-shadow",
    transitionDuration: "0.2s",
    ":hover": {
      ...shorthands.borderColor(semanticColors.borderAccent),
      transform: "translateY(-3px)",
      boxShadow: semanticColors.shadowMedium,
    },
  },
  imageWrap: {
    height: "180px",
    position: "relative",
    backgroundColor: semanticColors.bgTertiary,
  },
  image: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
    display: "block",
  },
  categoryPill: {
    position: "absolute",
    top: "12px",
    left: "12px",
    fontSize: typography.fontSize.size1,
    lineHeight: typography.lineHeight.normal,
    fontWeight: typography.fontWeight.bold,
    ...shorthands.padding("4px", "10px"),
    ...shorthands.borderRadius(layout.radius.full),
    backgroundColor: semanticColors.bgPrimary,
    color: semanticColors.textSecondary,
  },
  saveButton: {
    position: "absolute",
    top: "10px",
    right: "12px",
    width: "34px",
    height: "34px",
    ...shorthands.borderRadius(layout.radius.sm),
    ...shorthands.border("1px", "solid", semanticColors.borderLight),
    backgroundColor: "rgba(255, 255, 255, 0.9)",
    color: semanticColors.textSecondary,
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: typography.fontSize.size6,
    transitionProperty: "transform",
    transitionDuration: "0.2s",
    ":hover": {
      transform: "scale(1.05)",
    },
  },
  saveButtonActive: {
    color: colors.rose,
  },
  cardBody: {
    padding: "16px 18px 18px",
  },
  titleRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: layout.gap.xs,
    marginBottom: "6px",
  },
  cardTitle: {
    margin: 0,
    ...typographyPresets.h3,
    color: semanticColors.textPrimary,
    flex: 1,
  },
  ratingMeta: {
    display: "flex",
    alignItems: "center",
    gap: "4px",
    flexShrink: 0,
  },
  star: {
    color: colors.warning,
    fontSize: typography.fontSize.size3,
  },
  ratingValue: {
    fontSize: typography.fontSize.size3,
    color: semanticColors.textPrimary,
    fontWeight: typography.fontWeight.bold,
  },
  reviews: {
    fontSize: typography.fontSize.size2,
    color: semanticColors.textDisabled,
  },
  metaRow: {
    display: "flex",
    gap: "6px",
    alignItems: "center",
    marginBottom: "10px",
  },
  location: {
    fontSize: typography.fontSize.size2,
    color: semanticColors.textTertiary,
  },
  price: {
    marginLeft: "auto",
    fontSize: typography.fontSize.size2,
    color: colors.success,
    fontWeight: typography.fontWeight.semibold,
  },
  description: {
    margin: "0 0 14px",
    fontSize: typography.fontSize.size3,
    color: semanticColors.textSecondary,
    lineHeight: "1.65",
  },
  tags: {
    display: "flex",
    gap: "6px",
    flexWrap: "wrap",
    marginBottom: "14px",
  },
  tag: {
    fontSize: typography.fontSize.size1,
    fontWeight: typography.fontWeight.semibold,
    ...shorthands.padding("3px", "8px"),
    ...shorthands.borderRadius(layout.radius.full),
    backgroundColor: semanticColors.bgInteractiveSubtle,
    color: semanticColors.interactive,
  },
  actions: {
    display: "flex",
    gap: layout.gap.xs,
  },
  actionButton: {
    flex: 1,
    height: "38px",
    ...shorthands.borderRadius(layout.radius.sm),
    fontSize: typography.fontSize.size2,
    fontWeight: typography.fontWeight.semibold,
    cursor: "pointer",
    fontFamily: typography.fontFamily.sans,
  },
  primaryButton: {
    backgroundImage: gradients.primary,
    color: semanticColors.bgPrimary,
    border: "none",
  },
  secondaryButton: {
    backgroundColor: semanticColors.bgPrimary,
    color: semanticColors.textSecondary,
    ...shorthands.border("1.5px", "solid", semanticColors.borderDefault),
  },
  emptyState: {
    textAlign: "center",
    ...shorthands.padding("64px", "40px"),
  },
  emptyIcon: {
    fontSize: "48px",
    marginBottom: "16px",
  },
  emptyTitle: {
    fontSize: typography.fontSize.size8,
    fontWeight: typography.fontWeight.bold,
    color: semanticColors.textPrimary,
    marginBottom: "8px",
  },
  emptySubtitle: {
    fontSize: typography.fontSize.size4,
    color: semanticColors.textTertiary,
  },
});
