trigger: none

pr:
  branches:
    include:
      - "*"
  paths:
    include:
      - backend/**

variables:
  pythonVersion: "3.11"

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: $(pythonVersion)

- task: Cache@2
  inputs:
    key: 'pip | "$(Agent.OS)" | backend/requirements.txt'
    restoreKeys: |
      pip | "$(Agent.OS)"
    path: ~/.cache/pip

- script: |
    cd backend
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: Install backend dependencies

- script: |
    cd backend
    pip install ruff
    ruff check . --select F, D
  displayName: Check linting and docstrings

- script: |
    cd backend
    ruff format --check .
  displayName: Check code formatting

