import { makeStyles, shorthands } from "@griffel/react";
import {
  colors,
  warm,
  warmGradients,
  warmShadows,
} from "../../../common/theme/colors";
import { layout, typography } from "../../../common/theme/typography";

export const useChatbotStyles = makeStyles({
  page: {
    minHeight: "100vh",
    height: "100vh",
    overflow: "hidden",
    backgroundColor: warm.bgPage,
    color: warm.textPrimary,
    fontFamily: typography.fontFamily.ui,
    ...shorthands.padding(layout.padding.lg),
    "@media (max-width: 720px)": {
      ...shorthands.padding("0"),
    },
  },
  shell: {
    width: "100%",
    maxWidth: "1220px",
    height: "100%",
    marginLeft: "auto",
    marginRight: "auto",
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
    backgroundColor: warm.bgSurface,
    ...shorthands.border(layout.borderWidth.hairline, "solid", warm.border),
    ...shorthands.borderRadius(layout.radius["3xl"]),
    boxShadow: warmShadows.lg,
    "@media (max-width: 720px)": {
      maxWidth: "none",
      ...shorthands.border("0"),
      ...shorthands.borderRadius("0"),
    },
  },
  header: {
    position: "sticky",
    top: 0,
    zIndex: 2,
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: layout.gap.md,
    backgroundColor: warm.bgSurfaceBlur,
    backdropFilter: "blur(16px)",
    ...shorthands.borderBottom(
      layout.borderWidth.hairline,
      "solid",
      warm.border,
    ),
    ...shorthands.padding(layout.padding.md, layout.padding.lg),
    "@media (max-width: 560px)": {
      ...shorthands.padding(layout.padding.md),
    },
  },
  headerIdentity: {
    minWidth: 0,
    display: "flex",
    alignItems: "center",
    gap: layout.spacing[3.5],
  },
  aiIcon: {
    width: layout.controlSize["2xl"],
    height: layout.controlSize["2xl"],
    flexShrink: 0,
    color: colors.white,
    background: warmGradients.primary,
    boxShadow: warmShadows.roseHover,
  },
  title: {
    color: warm.textPrimary,
    fontSize: typography.fontSize.size9,
    lineHeight: "26px",
    fontWeight: 900,
    letterSpacing: "0",
    "@media (max-width: 560px)": {
      fontSize: typography.fontSize.size7,
      lineHeight: "23px",
    },
  },
  subtitle: {
    color: warm.textSecondary,
    fontSize: typography.fontSize.size3,
    lineHeight: "18px",
    fontWeight: typography.fontWeight.medium,
  },
  headerActions: {
    display: "flex",
    gap: layout.gap.xs,
  },
  headerButton: {
    width: layout.controlSize.xl,
    height: layout.controlSize.xl,
    color: warm.textSecondary,
    backgroundColor: colors.white,
    ...shorthands.border(layout.borderWidth.hairline, "solid", warm.border),
    boxShadow: warmShadows.xs,
    transitionProperty: "background-color, color, transform",
    transitionDuration: layout.duration.normal,
    ":hover": {
      backgroundColor: warm.bgTint,
      color: warm.coralBright,
      transform: "translateY(-1px)",
    },
  },
  messages: {
    flex: 1,
    minHeight: 0,
    overflowY: "auto",
    overflowX: "hidden",
    display: "flex",
    flexDirection: "column",
    gap: layout.spacing[4.5],
    ...shorthands.padding(layout.spacing[7], layout.padding.xl),
    "@media (max-width: 720px)": {
      ...shorthands.padding(layout.padding.md, layout.padding.md),
    },
  },
  emptyState: {
    marginTop: "auto",
    marginBottom: "auto",
    alignSelf: "center",
    width: "min(520px, 100%)",
    textAlign: "center",
    ...shorthands.padding(layout.padding.xl),
  },
  emptyIcon: {
    width: layout.controlSize["3xl"],
    height: layout.controlSize["3xl"],
    marginLeft: "auto",
    marginRight: "auto",
    marginBottom: layout.spacing[4],
    color: colors.white,
    background: warmGradients.primary,
  },
  emptyTitle: {
    color: warm.textPrimary,
    fontSize: typography.displaySize.sm,
    lineHeight: "31px",
    fontWeight: 900,
    marginBottom: layout.spacing[2],
  },
  emptyCopy: {
    color: warm.textSecondary,
    fontSize: typography.fontSize.size5,
    lineHeight: "23px",
  },
  messageRow: {
    display: "flex",
    alignItems: "flex-end",
    gap: layout.gap.sm,
  },
  assistantRow: {
    justifyContent: "flex-start",
  },
  userRow: {
    justifyContent: "flex-end",
  },
  avatar: {
    width: layout.controlSize.sm,
    height: layout.controlSize.sm,
    color: colors.white,
    background: warmGradients.primary,
    boxShadow: warmShadows.roseSoft,
  },
  bubble: {
    maxWidth: "68%",
    ...shorthands.borderRadius("26px"),
    ...shorthands.padding(layout.padding.md, "18px"),
    "@media (max-width: 920px)": {
      maxWidth: "78%",
    },
    "@media (max-width: 560px)": {
      maxWidth: "90%",
    },
  },
  assistantBubble: {
    backgroundColor: colors.white,
    ...shorthands.border(layout.borderWidth.hairline, "solid", warm.border),
    boxShadow: warmShadows.sm,
  },
  userBubble: {
    backgroundColor: warm.bgTint,
    ...shorthands.border(
      layout.borderWidth.hairline,
      "solid",
      warm.borderCoralBright,
    ),
  },
  messageText: {
    color: warm.textPrimary,
    fontSize: typography.fontSize.size5,
    lineHeight: "23px",
    whiteSpace: "pre-wrap",
    overflowWrap: "anywhere",
  },
  meta: {
    display: "flex",
    justifyContent: "flex-end",
    gap: layout.gap.xs,
    color: warm.textTertiary,
    fontSize: typography.fontSize.size1,
    lineHeight: "15px",
    fontWeight: 650,
    marginTop: layout.spacing[2.5],
  },
  previewCard: {
    marginTop: layout.spacing[3.5],
    overflow: "hidden",
    backgroundColor: warm.bgSurface,
    ...shorthands.border(layout.borderWidth.hairline, "solid", warm.border),
    ...shorthands.borderRadius("20px"),
  },
  previewImage: {
    width: "100%",
    height: "160px",
    objectFit: "cover",
    display: "block",
  },
  previewBody: {
    ...shorthands.padding(layout.padding.md),
  },
  previewTitle: {
    color: warm.textPrimary,
    fontSize: typography.fontSize.size7,
    lineHeight: "23px",
    fontWeight: 900,
    marginBottom: layout.spacing[2],
  },
  previewMeta: {
    display: "flex",
    flexWrap: "wrap",
    gap: layout.gap.xs,
    marginTop: layout.spacing[2.5],
  },
  pill: {
    color: warm.textBrand,
    backgroundColor: warm.bgTint,
    ...shorthands.border(layout.borderWidth.hairline, "solid", warm.border),
    ...shorthands.borderRadius(layout.radius.pill),
    ...shorthands.padding(layout.spacing[1.5], "10px"),
    fontSize: typography.fontSize.size2,
    lineHeight: "16px",
    fontWeight: 750,
  },
  previewButton: {
    marginTop: layout.spacing[3.5],
    color: colors.white,
    background: warmGradients.primary,
    ...shorthands.borderRadius(layout.radius.pill),
    textTransform: "none",
    fontWeight: 850,
    ":hover": {
      background: warmGradients.primaryHover,
    },
  },
  composerWrap: {
    position: "sticky",
    bottom: 0,
    zIndex: 2,
    backgroundColor: warm.bgSurfaceBlur,
    backdropFilter: "blur(16px)",
    ...shorthands.borderTop(layout.borderWidth.hairline, "solid", warm.border),
    ...shorthands.padding(layout.padding.md, layout.padding.lg, "18px"),
    "@media (max-width: 560px)": {
      ...shorthands.padding(layout.padding.sm),
    },
  },
  composer: {
    minHeight: layout.spacing[16],
    display: "flex",
    alignItems: "center",
    gap: layout.spacing[2.5],
    backgroundColor: colors.white,
    ...shorthands.border(layout.borderWidth.hairline, "solid", warm.border),
    ...shorthands.borderRadius(layout.radius["2xl"]),
    ...shorthands.padding(
      layout.padding.xs,
      layout.spacing[2.5],
      layout.padding.xs,
      "18px",
    ),
    boxShadow: warmShadows.md,
  },
  input: {
    flex: 1,
    color: warm.textPrimary,
    fontSize: typography.fontSize.size5,
    lineHeight: "22px",
  },
  sendButton: {
    width: layout.controlSize["2xl"],
    height: layout.controlSize["2xl"],
    color: colors.white,
    background: warmGradients.primary,
    boxShadow: warmShadows.rose,
    transitionProperty: "transform, box-shadow",
    transitionDuration: layout.duration.normal,
    ":hover": {
      background: warmGradients.primaryHover,
      transform: "translateY(-1px)",
    },
    ":disabled": {
      color: warm.textOnAccentDisabled,
      background: warm.bgDisabled,
      boxShadow: "none",
    },
  },
  disclaimer: {
    color: warm.textTertiary,
    fontSize: typography.fontSize.size2,
    lineHeight: "17px",
    textAlign: "center",
    marginTop: layout.spacing[2.5],
  },
});
