import { makeStyles, shorthands } from "@griffel/react";

const primaryGradient = "linear-gradient(135deg, #FF7A66 0%, #F43F7A 100%)";
const hoverGradient = "linear-gradient(135deg, #FF856F 0%, #F43F7A 100%)";

export const useChatbotStyles = makeStyles({
  page: {
    minHeight: "100vh",
    height: "100vh",
    overflow: "hidden",
    backgroundColor: "#FFF9F5",
    color: "#2F211B",
    fontFamily:
      "Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, \"Segoe UI\", sans-serif",
    ...shorthands.padding("24px"),
    "@media (max-width: 720px)": {
      ...shorthands.padding("0"),
    },
  },
  shell: {
    width: "100%",
    maxWidth: "1220px",
    height: "100%",
    marginLeft: "auto",
    marginRight: "auto",
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
    backgroundColor: "#FFFCF9",
    ...shorthands.border("1px", "solid", "#F3DED4"),
    ...shorthands.borderRadius("32px"),
    boxShadow: "0 24px 70px rgba(128, 73, 48, 0.13)",
    "@media (max-width: 720px)": {
      maxWidth: "none",
      ...shorthands.border("0"),
      ...shorthands.borderRadius("0"),
    },
  },
  header: {
    position: "sticky",
    top: 0,
    zIndex: 2,
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "16px",
    backgroundColor: "rgba(255, 252, 249, 0.96)",
    backdropFilter: "blur(16px)",
    ...shorthands.borderBottom("1px", "solid", "#F3DED4"),
    ...shorthands.padding("20px", "24px"),
    "@media (max-width: 560px)": {
      ...shorthands.padding("16px"),
    },
  },
  headerIdentity: {
    minWidth: 0,
    display: "flex",
    alignItems: "center",
    gap: "14px",
  },
  aiIcon: {
    width: "48px",
    height: "48px",
    flexShrink: 0,
    color: "#FFFFFF",
    background: primaryGradient,
    boxShadow: "0 14px 28px rgba(244, 63, 122, 0.25)",
  },
  title: {
    color: "#2F211B",
    fontSize: "20px",
    lineHeight: "26px",
    fontWeight: 900,
    letterSpacing: "0",
    "@media (max-width: 560px)": {
      fontSize: "17px",
      lineHeight: "23px",
    },
  },
  subtitle: {
    color: "#7F7068",
    fontSize: "13px",
    lineHeight: "18px",
    fontWeight: 500,
  },
  headerActions: {
    display: "flex",
    gap: "8px",
  },
  headerButton: {
    width: "42px",
    height: "42px",
    color: "#7F7068",
    backgroundColor: "#FFFFFF",
    ...shorthands.border("1px", "solid", "#F3DED4"),
    boxShadow: "0 8px 18px rgba(128, 73, 48, 0.07)",
    transitionProperty: "background-color, color, transform",
    transitionDuration: "180ms",
    ":hover": {
      backgroundColor: "#FFF1EB",
      color: "#FF6B6B",
      transform: "translateY(-1px)",
    },
  },
  messages: {
    flex: 1,
    minHeight: 0,
    overflowY: "auto",
    overflowX: "hidden",
    display: "flex",
    flexDirection: "column",
    gap: "18px",
    ...shorthands.padding("28px", "32px"),
    "@media (max-width: 720px)": {
      ...shorthands.padding("20px", "16px"),
    },
  },
  emptyState: {
    marginTop: "auto",
    marginBottom: "auto",
    alignSelf: "center",
    width: "min(520px, 100%)",
    textAlign: "center",
    ...shorthands.padding("32px"),
  },
  emptyIcon: {
    width: "58px",
    height: "58px",
    marginLeft: "auto",
    marginRight: "auto",
    marginBottom: "16px",
    color: "#FFFFFF",
    background: primaryGradient,
  },
  emptyTitle: {
    color: "#2F211B",
    fontSize: "24px",
    lineHeight: "31px",
    fontWeight: 900,
    marginBottom: "8px",
  },
  emptyCopy: {
    color: "#7F7068",
    fontSize: "15px",
    lineHeight: "23px",
  },
  messageRow: {
    display: "flex",
    alignItems: "flex-end",
    gap: "12px",
  },
  assistantRow: {
    justifyContent: "flex-start",
  },
  userRow: {
    justifyContent: "flex-end",
  },
  avatar: {
    width: "36px",
    height: "36px",
    color: "#FFFFFF",
    background: primaryGradient,
    boxShadow: "0 10px 20px rgba(244, 63, 122, 0.2)",
  },
  bubble: {
    maxWidth: "68%",
    ...shorthands.borderRadius("26px"),
    ...shorthands.padding("16px", "18px"),
    "@media (max-width: 920px)": {
      maxWidth: "78%",
    },
    "@media (max-width: 560px)": {
      maxWidth: "90%",
    },
  },
  assistantBubble: {
    backgroundColor: "#FFFFFF",
    ...shorthands.border("1px", "solid", "#F3DED4"),
    boxShadow: "0 14px 34px rgba(128, 73, 48, 0.08)",
  },
  userBubble: {
    backgroundColor: "#FFF1EB",
    ...shorthands.border("1px", "solid", "rgba(255, 107, 107, 0.3)"),
  },
  messageText: {
    color: "#2F211B",
    fontSize: "15px",
    lineHeight: "23px",
    whiteSpace: "pre-wrap",
    overflowWrap: "anywhere",
  },
  meta: {
    display: "flex",
    justifyContent: "flex-end",
    gap: "8px",
    color: "#9B8A82",
    fontSize: "11px",
    lineHeight: "15px",
    fontWeight: 650,
    marginTop: "10px",
  },
  previewCard: {
    marginTop: "14px",
    overflow: "hidden",
    backgroundColor: "#FFFCF9",
    ...shorthands.border("1px", "solid", "#F3DED4"),
    ...shorthands.borderRadius("20px"),
  },
  previewImage: {
    width: "100%",
    height: "160px",
    objectFit: "cover",
    display: "block",
  },
  previewBody: {
    ...shorthands.padding("16px"),
  },
  previewTitle: {
    color: "#2F211B",
    fontSize: "17px",
    lineHeight: "23px",
    fontWeight: 900,
    marginBottom: "8px",
  },
  previewMeta: {
    display: "flex",
    flexWrap: "wrap",
    gap: "8px",
    marginTop: "10px",
  },
  pill: {
    color: "#8B5A4B",
    backgroundColor: "#FFF1EB",
    ...shorthands.border("1px", "solid", "#F3DED4"),
    ...shorthands.borderRadius("999px"),
    ...shorthands.padding("6px", "10px"),
    fontSize: "12px",
    lineHeight: "16px",
    fontWeight: 750,
  },
  previewButton: {
    marginTop: "14px",
    color: "#FFFFFF",
    background: primaryGradient,
    ...shorthands.borderRadius("999px"),
    textTransform: "none",
    fontWeight: 850,
    ":hover": {
      background: hoverGradient,
    },
  },
  composerWrap: {
    position: "sticky",
    bottom: 0,
    zIndex: 2,
    backgroundColor: "rgba(255, 252, 249, 0.96)",
    backdropFilter: "blur(16px)",
    ...shorthands.borderTop("1px", "solid", "#F3DED4"),
    ...shorthands.padding("16px", "24px", "18px"),
    "@media (max-width: 560px)": {
      ...shorthands.padding("12px"),
    },
  },
  composer: {
    minHeight: "64px",
    display: "flex",
    alignItems: "center",
    gap: "10px",
    backgroundColor: "#FFFFFF",
    ...shorthands.border("1px", "solid", "#F3DED4"),
    ...shorthands.borderRadius("28px"),
    ...shorthands.padding("8px", "10px", "8px", "18px"),
    boxShadow: "0 18px 38px rgba(128, 73, 48, 0.1)",
  },
  input: {
    flex: 1,
    color: "#2F211B",
    fontSize: "15px",
    lineHeight: "22px",
  },
  sendButton: {
    width: "48px",
    height: "48px",
    color: "#FFFFFF",
    background: primaryGradient,
    boxShadow: "0 12px 24px rgba(244, 63, 122, 0.26)",
    transitionProperty: "transform, box-shadow",
    transitionDuration: "180ms",
    ":hover": {
      background: hoverGradient,
      transform: "translateY(-1px)",
    },
    ":disabled": {
      color: "rgba(255, 255, 255, 0.78)",
      background: "#E8CBC1",
      boxShadow: "none",
    },
  },
  disclaimer: {
    color: "#9B8A82",
    fontSize: "12px",
    lineHeight: "17px",
    textAlign: "center",
    marginTop: "10px",
  },
});
