import { makeStyles, shorthands } from "@griffel/react";

export const useItineraryStyles = makeStyles({
  page: {
    minHeight: "100vh",
    backgroundColor: "#f8fbff",
    color: "#020b22",
    fontFamily:
      "Cairo, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, \"Segoe UI\", sans-serif",
  },
  loading: {
    minHeight: "70vh",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: "14px",
  },
  loadingMessage: {
    color: "#52688c",
    fontSize: "14px",
    lineHeight: "20px",
    fontWeight: 700,
  },
  shell: {
    maxWidth: "none",
    ...shorthands.padding("33px", "27px", "16px"),
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: "24px",
    marginBottom: "28px",
  },
  titleRow: {
    display: "flex",
    alignItems: "center",
    gap: "11px",
  },
  planeIcon: {
    color: "#58c982",
    fontSize: "31px",
    transform: "rotate(-23deg)",
  },
  title: {
    fontSize: "24px",
    lineHeight: "30px",
    fontWeight: 800,
    letterSpacing: "0",
  },
  generatedBadge: {
    height: "22px",
    display: "inline-flex",
    alignItems: "center",
    ...shorthands.padding("0", "9px"),
    ...shorthands.borderRadius("999px"),
    backgroundColor: "#d9f8e5",
    color: "#13bf5d",
    fontSize: "10px",
    lineHeight: "14px",
    fontWeight: 800,
  },
  subtitle: {
    marginTop: "9px",
    color: "#52688c",
    fontSize: "13px",
    lineHeight: "18px",
    fontWeight: 400,
  },
  emptyState: {
    width: "min(560px, 100%)",
    marginTop: "160px",
    marginLeft: "auto",
    marginRight: "auto",
    textAlign: "center",
    ...shorthands.padding("28px", "32px"),
    ...shorthands.border("1px", "solid", "#d9e4f1"),
    ...shorthands.borderRadius("12px"),
    backgroundColor: "#ffffff",
    boxShadow: "0 2px 8px rgba(20, 43, 76, 0.05)",
  },
  emptyTitle: {
    color: "#020b22",
    fontSize: "18px",
    lineHeight: "24px",
    fontWeight: 800,
    marginBottom: "8px",
  },
  emptyMessage: {
    color: "#52688c",
    fontSize: "14px",
    lineHeight: "21px",
    fontWeight: 500,
  },
  headerActions: {
    display: "flex",
    gap: "10px",
  },
  button: {
    height: "39px",
    minWidth: "91px",
    ...shorthands.borderRadius("10px"),
    textTransform: "none",
    fontSize: "12px",
    fontWeight: 700,
    boxShadow: "none",
  },
  ghostButton: {
    color: "#0f1f39",
    backgroundColor: "#ffffff",
    ...shorthands.border("1px", "solid", "#dce5f2"),
    ":hover": {
      backgroundColor: "#ffffff",
      boxShadow: "none",
    },
  },
  primaryButton: {
    minWidth: "110px",
    color: "#ffffff",
    background: "linear-gradient(135deg, #10b6dc 0%, #3578f4 100%)",
    ":hover": {
      background: "linear-gradient(135deg, #10b6dc 0%, #3578f4 100%)",
      boxShadow: "none",
    },
  },
  dayTabs: {
    display: "flex",
    gap: "8px",
    marginBottom: "27px",
  },
  dayTab: {
    width: "93px",
    height: "54px",
    ...shorthands.borderRadius("28px"),
    ...shorthands.border("1px", "solid", "#d9e4f4"),
    backgroundColor: "#ffffff",
    color: "#5e6f8d",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    fontWeight: 800,
    fontSize: "12px",
    lineHeight: "16px",
  },
  dayTabActive: {
    background: "linear-gradient(135deg, #12b8dc 0%, #287ff2 100%)",
    color: "#ffffff",
    ...shorthands.borderColor("transparent"),
    boxShadow: "0 9px 17px rgba(24, 157, 221, 0.34)",
  },
  dayDate: {
    fontSize: "9px",
    lineHeight: "13px",
    fontWeight: 700,
    color: "inherit",
  },
  sectionBar: {
    height: "61px",
    ...shorthands.border("1px", "solid", "#d9e4f1"),
    ...shorthands.borderRadius("11px"),
    backgroundColor: "#ffffff",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    ...shorthands.padding("0", "19px"),
    marginBottom: "16px",
  },
  sectionTitle: {
    fontSize: "15px",
    lineHeight: "20px",
    fontWeight: 800,
  },
  sectionActions: {
    display: "flex",
    gap: "10px",
  },
  compactButton: {
    height: "32px",
    ...shorthands.borderRadius("10px"),
    textTransform: "none",
    fontSize: "11px",
    fontWeight: 800,
    boxShadow: "none",
    ...shorthands.padding("0", "14px"),
  },
  outlineBlueButton: {
    color: "#02a8d8",
    backgroundColor: "#ffffff",
    ...shorthands.border("1px", "solid", "#02a8d8"),
    ":hover": {
      backgroundColor: "#ffffff",
      boxShadow: "none",
    },
  },
  timeline: {
    position: "relative",
    paddingLeft: "56px",
  },
  connector: {
    position: "absolute",
    left: "24px",
    top: "0",
    bottom: "0",
    width: "2px",
    background:
      "linear-gradient(180deg, #13c861 0%, #237cff 55%, #ffab2e 100%)",
    opacity: 0.9,
  },
  activityRow: {
    position: "relative",
    marginBottom: "15px",
  },
  marker: {
    position: "absolute",
    left: "-56px",
    top: "0",
    width: "36px",
    height: "36px",
    ...shorthands.borderRadius("12px"),
    backgroundColor: "#ffffff",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    boxShadow: "0 0 0 4px #eef7ff, 0 1px 5px rgba(33, 79, 130, 0.16)",
  },
  markerGreen: {
    color: "#48bf56",
    ...shorthands.border("1px", "solid", "#22cf62"),
  },
  markerBlue: {
    color: "#2d79ff",
    ...shorthands.border("1px", "solid", "#347cff"),
  },
  markerOrange: {
    color: "#ff8f2b",
    ...shorthands.border("1px", "solid", "#ffae30"),
  },
  activityCard: {
    minHeight: "135px",
    ...shorthands.border("1px", "solid", "#dde6f2"),
    ...shorthands.borderRadius("12px"),
    backgroundColor: "#ffffff",
    boxShadow: "0 2px 5px rgba(20, 43, 76, 0.06)",
    display: "flex",
    justifyContent: "space-between",
    gap: "20px",
    ...shorthands.padding("17px", "18px", "15px", "20px"),
  },
  activityMeta: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    marginBottom: "7px",
  },
  category: {
    height: "18px",
    display: "inline-flex",
    alignItems: "center",
    ...shorthands.padding("0", "8px"),
    ...shorthands.borderRadius("999px"),
    backgroundColor: "#e8fff0",
    color: "#12c861",
    fontSize: "9px",
    lineHeight: "12px",
    fontWeight: 900,
    textTransform: "uppercase",
  },
  categoryBlue: {
    backgroundColor: "#edf3ff",
    color: "#4f74ff",
  },
  categoryOrange: {
    backgroundColor: "#fff4e7",
    color: "#ff8a1a",
  },
  activityTitle: {
    color: "#020b22",
    fontSize: "15px",
    lineHeight: "20px",
    fontWeight: 800,
    marginBottom: "13px",
  },
  detailLine: {
    display: "flex",
    alignItems: "center",
    gap: "18px",
    color: "#536a8f",
    fontSize: "11px",
    lineHeight: "15px",
  },
  detailItem: {
    display: "inline-flex",
    alignItems: "center",
    gap: "5px",
    whiteSpace: "nowrap",
  },
  detailIcon: {
    color: "#e93e79",
    fontSize: "14px",
  },
  cardActions: {
    display: "flex",
    gap: "7px",
    flexShrink: 0,
  },
  iconButton: {
    width: "28px",
    height: "28px",
    ...shorthands.border("1px", "solid", "#dde6f2"),
    ...shorthands.borderRadius("7px"),
    backgroundColor: "#ffffff",
  },
  editIcon: {
    color: "#ff7d3b",
    fontSize: "16px",
  },
  calendarIcon: {
    color: "#267df0",
    fontSize: "16px",
  },
  deleteIcon: {
    color: "#8895ad",
    fontSize: "16px",
  },
});
