import { makeStyles, shorthands } from "@griffel/react";

const coralGradient = "linear-gradient(135deg, #ff6b6b 0%, #f06292 100%)";
const peachGradient =
  "linear-gradient(135deg, #ff8a65 0%, #ff6b6b 52%, #f06292 100%)";

export const useItineraryStyles = makeStyles({
  page: {
    minHeight: "100vh",
    color: "#281a18",
    background:
      "radial-gradient(circle at 8% 0%, rgba(255, 138, 101, 0.18), transparent 34%), radial-gradient(circle at 86% 10%, rgba(240, 98, 146, 0.15), transparent 31%), linear-gradient(180deg, #fff8f3 0%, #fffaf6 48%, #f8efe7 100%)",
    fontFamily:
      "Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, \"Segoe UI\", sans-serif",
  },
  loading: {
    minHeight: "70vh",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: "16px",
  },
  loadingMessage: {
    color: "#8d6e63",
    fontSize: "14px",
    lineHeight: "20px",
    fontWeight: 700,
  },
  shell: {
    maxWidth: "none",
    ...shorthands.padding("0"),
  },
  layout: {
    display: "grid",
    gridTemplateAreas: "\"main summary\"",
    gridTemplateColumns: "minmax(720px, 1fr) 304px",
    minHeight: "100vh",
    "@media (max-width: 980px)": {
      gridTemplateAreas: "\"summary\" \"main\"",
      gridTemplateColumns: "1fr",
    },
  },
  mainContent: {
    gridArea: "main",
    minWidth: 0,
    ...shorthands.padding("40px", "40px", "28px"),
    "@media (max-width: 720px)": {
      ...shorthands.padding("24px", "16px", "20px"),
    },
  },
  summarySidebar: {
    gridArea: "summary",
    minHeight: "100vh",
    background:
      "linear-gradient(180deg, rgba(255,255,255,0.72) 0%, rgba(255,248,243,0.92) 100%)",
    backdropFilter: "blur(18px)",
    ...shorthands.borderLeft("1px", "solid", "rgba(255, 107, 107, 0.16)"),
    ...shorthands.padding("32px", "22px"),
    boxShadow: "-18px 0 45px rgba(127, 69, 45, 0.06)",
    "@media (max-width: 980px)": {
      minHeight: "auto",
      ...shorthands.borderLeft("0"),
      ...shorthands.borderBottom("1px", "solid", "rgba(255, 107, 107, 0.16)"),
    },
  },
  summaryTitle: {
    color: "#2d1b18",
    fontSize: "18px",
    lineHeight: "24px",
    fontWeight: 850,
    marginBottom: "22px",
  },
  summaryCards: {
    display: "grid",
    gap: "16px",
    marginBottom: "22px",
    "@media (max-width: 980px)": {
      gridTemplateColumns: "repeat(4, minmax(0, 1fr))",
    },
    "@media (max-width: 760px)": {
      gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
    },
    "@media (max-width: 480px)": {
      gridTemplateColumns: "1fr",
    },
  },
  summaryCard: {
    position: "relative",
    minHeight: "128px",
    backgroundColor: "rgba(255, 252, 248, 0.9)",
    ...shorthands.border("1px", "solid", "rgba(255, 138, 101, 0.14)"),
    ...shorthands.borderRadius("22px"),
    ...shorthands.padding("18px", "16px", "16px"),
    boxShadow: "0 18px 38px rgba(140, 82, 54, 0.09)",
  },
  summaryCheck: {
    position: "absolute",
    top: "16px",
    right: "16px",
    color: "#22b66f",
    fontSize: "14px",
    lineHeight: "14px",
    fontWeight: 900,
  },
  summaryValue: {
    color: "#2d1b18",
    fontSize: "24px",
    lineHeight: "30px",
    fontWeight: 900,
    marginTop: "18px",
  },
  summaryLabel: {
    color: "#f06292",
    fontSize: "11px",
    lineHeight: "15px",
    fontWeight: 800,
    marginTop: "2px",
    textTransform: "uppercase",
  },
  summaryNote: {
    color: "#8b7067",
    fontSize: "12px",
    lineHeight: "17px",
    fontWeight: 500,
    marginTop: "4px",
  },
  summaryMoneyIcon: { color: "#ff8a65", fontSize: "22px" },
  summaryCalendarIcon: { color: "#f06292", fontSize: "22px" },
  summaryTargetIcon: { color: "#ff6b6b", fontSize: "22px" },
  summaryTravelersIcon: { color: "#c76b55", fontSize: "22px" },
  budgetRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    color: "#8d6e63",
    fontSize: "12px",
    lineHeight: "17px",
    fontWeight: 800,
    marginBottom: "10px",
  },
  progressTrack: {
    height: "8px",
    overflow: "hidden",
    backgroundColor: "#f2dfd2",
    ...shorthands.borderRadius("999px"),
    marginBottom: "22px",
  },
  progressFill: {
    height: "100%",
    background: coralGradient,
    ...shorthands.borderRadius("999px"),
  },
  modifyTripButton: {
    width: "100%",
    height: "52px",
    color: "#ffffff",
    background: coralGradient,
    ...shorthands.borderRadius("999px"),
    textTransform: "none",
    fontSize: "14px",
    lineHeight: "20px",
    fontWeight: 850,
    boxShadow: "0 18px 34px rgba(240, 98, 146, 0.28)",
    marginBottom: "14px",
    ":hover": {
      background: peachGradient,
      boxShadow: "0 20px 38px rgba(240, 98, 146, 0.34)",
    },
  },
  modifyTripIcon: { color: "#fff5ec", fontSize: "18px" },
  exportButton: {
    width: "100%",
    height: "48px",
    color: "#4d342f",
    backgroundColor: "rgba(255,255,255,0.78)",
    ...shorthands.border("1px", "solid", "rgba(255, 138, 101, 0.22)"),
    ...shorthands.borderRadius("999px"),
    textTransform: "none",
    fontSize: "13px",
    lineHeight: "18px",
    fontWeight: 850,
    boxShadow: "0 12px 26px rgba(140, 82, 54, 0.07)",
    ":hover": {
      backgroundColor: "#ffffff",
      boxShadow: "0 16px 30px rgba(140, 82, 54, 0.1)",
    },
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: "24px",
    marginBottom: "32px",
    "@media (max-width: 760px)": {
      flexDirection: "column",
    },
  },
  titleRow: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
    flexWrap: "wrap",
  },
  planeIcon: {
    color: "#ff6b6b",
    fontSize: "34px",
    transform: "rotate(-18deg)",
    filter: "drop-shadow(0 8px 14px rgba(255, 107, 107, 0.22))",
  },
  title: {
    color: "#281a18",
    fontSize: "40px",
    lineHeight: "46px",
    fontWeight: 900,
    letterSpacing: "0",
    "@media (max-width: 560px)": {
      fontSize: "30px",
      lineHeight: "36px",
    },
  },
  generatedBadge: {
    height: "26px",
    display: "inline-flex",
    alignItems: "center",
    ...shorthands.padding("0", "12px"),
    ...shorthands.borderRadius("999px"),
    backgroundColor: "#fff0ea",
    color: "#ff6b6b",
    fontSize: "10px",
    lineHeight: "14px",
    fontWeight: 900,
    textTransform: "uppercase",
  },
  subtitle: {
    marginTop: "12px",
    color: "#83665c",
    fontSize: "15px",
    lineHeight: "22px",
    fontWeight: 500,
  },
  emptyState: {
    width: "min(560px, 100%)",
    marginTop: "150px",
    marginLeft: "auto",
    marginRight: "auto",
    textAlign: "center",
    ...shorthands.padding("32px"),
    ...shorthands.border("1px", "solid", "rgba(255, 138, 101, 0.18)"),
    ...shorthands.borderRadius("24px"),
    backgroundColor: "rgba(255, 252, 248, 0.88)",
    boxShadow: "0 24px 55px rgba(140, 82, 54, 0.1)",
  },
  emptyTitle: {
    color: "#2d1b18",
    fontSize: "20px",
    lineHeight: "28px",
    fontWeight: 900,
    marginBottom: "8px",
  },
  emptyMessage: {
    color: "#8d6e63",
    fontSize: "14px",
    lineHeight: "22px",
    fontWeight: 500,
  },
  headerActions: {
    display: "flex",
    gap: "12px",
    flexWrap: "wrap",
  },
  button: {
    height: "44px",
    minWidth: "108px",
    ...shorthands.borderRadius("999px"),
    textTransform: "none",
    fontSize: "13px",
    fontWeight: 850,
    boxShadow: "none",
    transitionProperty: "transform, box-shadow, background",
    transitionDuration: "180ms",
    ":hover": {
      transform: "translateY(-1px)",
    },
  },
  ghostButton: {
    color: "#4d342f",
    backgroundColor: "rgba(255,255,255,0.76)",
    ...shorthands.border("1px", "solid", "rgba(255, 138, 101, 0.22)"),
    ":hover": {
      backgroundColor: "#ffffff",
      boxShadow: "0 14px 28px rgba(140, 82, 54, 0.1)",
    },
  },
  primaryButton: {
    minWidth: "122px",
    color: "#ffffff",
    background: coralGradient,
    boxShadow: "0 16px 32px rgba(240, 98, 146, 0.26)",
    ":hover": {
      background: peachGradient,
      boxShadow: "0 18px 36px rgba(240, 98, 146, 0.32)",
    },
  },
  dayTabs: {
    display: "flex",
    gap: "12px",
    marginBottom: "28px",
    overflowX: "auto",
    paddingBottom: "4px",
  },
  dayTab: {
    width: "112px",
    height: "62px",
    flexShrink: 0,
    ...shorthands.borderRadius("999px"),
    ...shorthands.border("1px", "solid", "rgba(255, 138, 101, 0.2)"),
    backgroundColor: "rgba(255, 252, 248, 0.84)",
    color: "#8d6e63",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    fontWeight: 900,
    fontSize: "13px",
    lineHeight: "18px",
    boxShadow: "0 10px 26px rgba(140, 82, 54, 0.06)",
    transitionProperty: "transform, box-shadow, background, color",
    transitionDuration: "180ms",
    ":hover": {
      transform: "translateY(-1px)",
      boxShadow: "0 14px 30px rgba(140, 82, 54, 0.1)",
    },
  },
  dayTabActive: {
    background: coralGradient,
    color: "#ffffff !important",
    ...shorthands.borderColor("transparent"),
    boxShadow: "0 16px 34px rgba(240, 98, 146, 0.3)",
  },
  dayDate: {
    fontSize: "10px",
    lineHeight: "14px",
    fontWeight: 800,
    color: "inherit",
  },
  sectionBar: {
    minHeight: "72px",
    ...shorthands.border("1px", "solid", "rgba(255, 138, 101, 0.16)"),
    ...shorthands.borderRadius("24px"),
    backgroundColor: "rgba(255, 252, 248, 0.86)",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "16px",
    ...shorthands.padding("14px", "18px", "14px", "22px"),
    marginBottom: "22px",
    boxShadow: "0 18px 42px rgba(140, 82, 54, 0.08)",
    "@media (max-width: 680px)": {
      alignItems: "flex-start",
      flexDirection: "column",
    },
  },
  sectionTitle: {
    color: "#2d1b18",
    fontSize: "18px",
    lineHeight: "24px",
    fontWeight: 900,
  },
  sectionActions: {
    display: "flex",
    gap: "10px",
    flexWrap: "wrap",
  },
  compactButton: {
    height: "38px",
    ...shorthands.borderRadius("999px"),
    textTransform: "none",
    fontSize: "12px",
    fontWeight: 850,
    boxShadow: "none",
    ...shorthands.padding("0", "16px"),
  },
  outlineBlueButton: {
    color: "#ff6b6b",
    backgroundColor: "#ffffff",
    ...shorthands.border("1px", "solid", "rgba(255, 107, 107, 0.36)"),
    ":hover": {
      backgroundColor: "#fff5ef",
      boxShadow: "0 12px 26px rgba(240, 98, 146, 0.12)",
    },
  },
  regenerateIcon: { color: "#ff8a65" },
  timeline: {
    position: "relative",
    paddingLeft: "58px",
    "@media (max-width: 560px)": {
      paddingLeft: "42px",
    },
  },
  connector: {
    position: "absolute",
    left: "24px",
    top: "0",
    bottom: "0",
    width: "2px",
    background:
      "linear-gradient(180deg, rgba(255,107,107,0.95) 0%, rgba(240,98,146,0.88) 58%, rgba(255,138,101,0.32) 100%)",
    opacity: 0.9,
    "@media (max-width: 560px)": {
      left: "18px",
    },
  },
  activityRow: {
    position: "relative",
    marginBottom: "18px",
  },
  marker: {
    position: "absolute",
    left: "-58px",
    top: "5px",
    width: "42px",
    height: "42px",
    ...shorthands.borderRadius("16px"),
    backgroundColor: "#fffaf6",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    boxShadow:
      "0 0 0 5px rgba(255, 240, 234, 0.9), 0 10px 22px rgba(140, 82, 54, 0.14)",
    "@media (max-width: 560px)": {
      left: "-42px",
      width: "34px",
      height: "34px",
      ...shorthands.borderRadius("13px"),
    },
  },
  markerIcon: {
    fontSize: "20px",
    "@media (max-width: 560px)": {
      fontSize: "17px",
    },
  },
  markerGreen: {
    color: "#55b878",
    ...shorthands.border("1px", "solid", "#ffd6c9"),
  },
  markerPurple: {
    color: "#ff8a65",
    ...shorthands.border("1px", "solid", "#ffc7bc"),
  },
  markerBlue: {
    color: "#f06292",
    ...shorthands.border("1px", "solid", "#ffd1df"),
  },
  markerCyan: {
    color: "#ff6b6b",
    ...shorthands.border("1px", "solid", "#ffc6bd"),
  },
  markerOrange: {
    color: "#ff8a65",
    ...shorthands.border("1px", "solid", "#ffd5ad"),
  },
  markerRed: {
    color: "#c76b55",
    ...shorthands.border("1px", "solid", "#ffc4c4"),
  },
  activityCard: {
    minHeight: "142px",
    ...shorthands.border("1px", "solid", "rgba(255, 138, 101, 0.16)"),
    ...shorthands.borderRadius("26px"),
    backgroundColor: "rgba(255, 252, 248, 0.9)",
    boxShadow: "0 20px 48px rgba(140, 82, 54, 0.1)",
    display: "flex",
    justifyContent: "space-between",
    gap: "20px",
    ...shorthands.padding("22px", "22px", "20px", "24px"),
    transitionProperty: "transform, box-shadow",
    transitionDuration: "180ms",
    ":hover": {
      transform: "translateY(-2px)",
      boxShadow: "0 24px 56px rgba(140, 82, 54, 0.14)",
    },
    "@media (max-width: 620px)": {
      flexDirection: "column",
      ...shorthands.padding("18px"),
    },
  },
  activityContent: {
    minWidth: 0,
  },
  activityMeta: {
    display: "flex",
    alignItems: "center",
    gap: "9px",
    flexWrap: "wrap",
    marginBottom: "9px",
  },
  category: {
    height: "22px",
    display: "inline-flex",
    alignItems: "center",
    ...shorthands.padding("0", "10px"),
    ...shorthands.borderRadius("999px"),
    backgroundColor: "#fff0ea",
    color: "#ff6b6b",
    fontSize: "10px",
    lineHeight: "14px",
    fontWeight: 900,
    textTransform: "uppercase",
  },
  categoryBlue: {
    backgroundColor: "#fceaf2",
    color: "#f06292",
  },
  categoryGreen: {
    backgroundColor: "#eef8ec",
    color: "#55a66d",
  },
  categoryAmber: {
    backgroundColor: "#fff3df",
    color: "#ff8a65",
  },
  categoryOrange: {
    backgroundColor: "#fff3df",
    color: "#ff8a65",
  },
  categoryRed: {
    backgroundColor: "#ffecef",
    color: "#ff6b6b",
  },
  activityTime: {
    color: "#9b7c72",
    fontSize: "12px",
    lineHeight: "17px",
    fontWeight: 750,
  },
  activityTitle: {
    color: "#281a18",
    fontSize: "18px",
    lineHeight: "25px",
    fontWeight: 900,
    marginBottom: "12px",
  },
  activityDescription: {
    color: "#74574e",
    fontSize: "14px",
    lineHeight: "22px",
    fontWeight: 450,
    marginBottom: "16px",
  },
  detailLine: {
    display: "flex",
    alignItems: "center",
    gap: "16px",
    flexWrap: "wrap",
    color: "#7e6259",
    fontSize: "12px",
    lineHeight: "17px",
  },
  detailItem: {
    display: "inline-flex",
    alignItems: "center",
    gap: "6px",
    whiteSpace: "nowrap",
  },
  detailIcon: { color: "#f06292", fontSize: "15px" },
  trainIcon: { color: "#ff8a65", fontSize: "15px" },
  mutedIcon: { color: "#a98a80", fontSize: "15px" },
  costIcon: { color: "#ff8a65", fontSize: "15px" },
  weatherIcon: { color: "#9b7c72", fontSize: "15px" },
  cardActions: {
    display: "flex",
    gap: "8px",
    flexShrink: 0,
    "@media (max-width: 620px)": {
      alignSelf: "flex-end",
    },
  },
  iconButton: {
    width: "34px",
    height: "34px",
    ...shorthands.border("1px", "solid", "rgba(255, 138, 101, 0.2)"),
    ...shorthands.borderRadius("12px"),
    backgroundColor: "#ffffff",
    boxShadow: "0 8px 18px rgba(140, 82, 54, 0.06)",
    ":hover": {
      backgroundColor: "#fff4ee",
    },
  },
  editIcon: { color: "#ff8a65", fontSize: "17px" },
  calendarIcon: { color: "#f06292", fontSize: "17px" },
  deleteIcon: { color: "#a98a80", fontSize: "17px" },
});
