import { makeStyles, shorthands } from "@griffel/react";
import {
  colors,
  itinerary,
  itineraryGradients,
  itineraryShadows,
  warm,
  warmGradients,
  warmShadows,
} from "../../../common/theme/colors";
import { layout, typography } from "../../../common/theme/typography";

export const useItineraryStyles = makeStyles({
  page: {
    minHeight: "100vh",
    color: itinerary.textDarkest,
    background: itineraryGradients.page,
    fontFamily: typography.fontFamily.ui,
  },
  loading: {
    minHeight: "70vh",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: layout.gap.md,
  },
  loadingMessage: {
    color: itinerary.textSecondary,
    fontSize: typography.fontSize.size4,
    lineHeight: "20px",
    fontWeight: typography.fontWeight.bold,
  },
  shell: {
    maxWidth: "none",
    ...shorthands.padding("0"),
  },
  layout: {
    display: "grid",
    gridTemplateAreas: "'main summary'",
    gridTemplateColumns: "minmax(720px, 1fr) 304px",
    minHeight: "100vh",
    "@media (max-width: 980px)": {
      gridTemplateAreas: "'summary' 'main'",
      gridTemplateColumns: "1fr",
    },
  },
  noSummaryLayout: {
    gridTemplateAreas: "'main'",
    gridTemplateColumns: "1fr",
  },
  mainContent: {
    gridArea: "main",
    minWidth: 0,
    ...shorthands.padding(layout.spacing[10], layout.spacing[10], "28px"),
    "@media (max-width: 720px)": {
      ...shorthands.padding(
        layout.padding.lg,
        layout.padding.md,
        layout.spacing[5],
      ),
    },
  },
  centeredMainContent: {
    minHeight: "calc(100vh - 126px)",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
  },
  summarySidebar: {
    gridArea: "summary",
    minHeight: "100vh",
    background: itineraryGradients.sidebar,
    backdropFilter: "blur(18px)",
    ...shorthands.borderLeft(
      layout.borderWidth.hairline,
      "solid",
      itinerary.borderCoral,
    ),
    ...shorthands.padding(layout.padding.xl, "22px"),
    boxShadow: itineraryShadows.sidebar,
    "@media (max-width: 980px)": {
      minHeight: "auto",
      ...shorthands.borderLeft("0"),
      ...shorthands.borderBottom(
        layout.borderWidth.hairline,
        "solid",
        itinerary.borderCoral,
      ),
    },
  },
  summaryTitle: {
    color: itinerary.textDark,
    fontSize: typography.fontSize.size8,
    lineHeight: "24px",
    fontWeight: 850,
    marginBottom: layout.spacing[5.5],
  },
  summaryCards: {
    display: "grid",
    gap: layout.gap.md,
    marginBottom: layout.spacing[5.5],
    "@media (max-width: 980px)": {
      gridTemplateColumns: "repeat(4, minmax(0, 1fr))",
    },
    "@media (max-width: 760px)": {
      gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
    },
    "@media (max-width: 480px)": {
      gridTemplateColumns: "1fr",
    },
  },
  summaryCard: {
    position: "relative",
    minHeight: "128px",
    backgroundColor: itinerary.surfaceCard,
    ...shorthands.border(
      layout.borderWidth.hairline,
      "solid",
      itinerary.borderPeach14,
    ),
    ...shorthands.borderRadius("22px"),
    ...shorthands.padding(
      layout.spacing[4.5],
      layout.padding.md,
      layout.padding.md,
    ),
    boxShadow: itineraryShadows.summaryCard,
  },
  summaryCheck: {
    position: "absolute",
    top: layout.spacing[4],
    right: layout.spacing[4],
    color: itinerary.check,
    fontSize: typography.fontSize.size4,
    lineHeight: "14px",
    fontWeight: 900,
  },
  summaryValue: {
    color: itinerary.textDark,
    fontSize: typography.displaySize.sm,
    lineHeight: "30px",
    fontWeight: 900,
    marginTop: layout.spacing[4.5],
  },
  summaryLabel: {
    color: itinerary.pink,
    fontSize: typography.fontSize.size1,
    lineHeight: "15px",
    fontWeight: 800,
    marginTop: "2px",
    textTransform: "uppercase",
  },
  summaryNote: {
    color: itinerary.textFaint,
    fontSize: typography.fontSize.size2,
    lineHeight: "17px",
    fontWeight: typography.fontWeight.medium,
    marginTop: layout.spacing[1],
  },
  summaryMoneyIcon: {
    color: itinerary.peach,
    fontSize: typography.fontSize.size10,
  },
  summaryCalendarIcon: {
    color: itinerary.pink,
    fontSize: typography.fontSize.size10,
  },
  summaryTargetIcon: {
    color: warm.coralBright,
    fontSize: typography.fontSize.size10,
  },
  summaryTravelersIcon: {
    color: itinerary.clay,
    fontSize: typography.fontSize.size10,
  },
  budgetRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    color: itinerary.textSecondary,
    fontSize: typography.fontSize.size2,
    lineHeight: "17px",
    fontWeight: 800,
    marginBottom: layout.spacing[2.5],
  },
  progressTrack: {
    height: layout.spacing[2],
    overflow: "hidden",
    backgroundColor: itinerary.track,
    ...shorthands.borderRadius(layout.radius.pill),
    marginBottom: layout.spacing[5.5],
  },
  progressFill: {
    height: "100%",
    background: itineraryGradients.coral,
    ...shorthands.borderRadius(layout.radius.pill),
  },
  modifyTripButton: {
    width: "100%",
    height: "52px",
    color: colors.white,
    background: itineraryGradients.coral,
    ...shorthands.borderRadius(layout.radius.pill),
    textTransform: "none",
    fontSize: typography.fontSize.size4,
    lineHeight: "20px",
    fontWeight: 850,
    boxShadow: itineraryShadows.modifyTrip,
    marginBottom: layout.spacing[3.5],
    ":hover": {
      background: itineraryGradients.peach,
      boxShadow: itineraryShadows.modifyTripHover,
    },
  },
  modifyTripIcon: {
    color: itinerary.iconOnPrimary,
    fontSize: typography.fontSize.size8,
  },
  exportButton: {
    width: "100%",
    height: layout.controlSize["2xl"],
    color: itinerary.textStrong,
    backgroundColor: itinerary.surfaceTranslucent,
    ...shorthands.border(
      layout.borderWidth.hairline,
      "solid",
      itinerary.borderPeach22,
    ),
    ...shorthands.borderRadius(layout.radius.pill),
    textTransform: "none",
    fontSize: typography.fontSize.size3,
    lineHeight: "18px",
    fontWeight: 850,
    boxShadow: itineraryShadows.export,
    ":hover": {
      backgroundColor: colors.white,
      boxShadow: itineraryShadows.exportHover,
    },
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: layout.gap.lg,
    marginBottom: layout.spacing[8],
    "@media (max-width: 760px)": {
      flexDirection: "column",
    },
  },
  titleRow: {
    display: "flex",
    alignItems: "center",
    gap: layout.gap.sm,
    flexWrap: "wrap",
  },
  planeIcon: {
    color: warm.coralBright,
    fontSize: typography.fontSize.size12,
    transform: "rotate(-18deg)",
    filter: itineraryShadows.planeIcon,
  },
  title: {
    color: itinerary.textDarkest,
    fontSize: typography.displaySize.lg,
    lineHeight: "46px",
    fontWeight: 900,
    letterSpacing: "0",
    "@media (max-width: 560px)": {
      fontSize: typography.displaySize.md,
      lineHeight: "36px",
    },
  },
  generatedBadge: {
    height: layout.spacing[6.5],
    display: "inline-flex",
    alignItems: "center",
    ...shorthands.padding("0", layout.padding.sm),
    ...shorthands.borderRadius(layout.radius.pill),
    backgroundColor: itinerary.bgBadge,
    color: warm.coralBright,
    fontSize: typography.fontSize.size0,
    lineHeight: "14px",
    fontWeight: 900,
    textTransform: "uppercase",
  },
  subtitle: {
    marginTop: layout.spacing[3],
    color: itinerary.textSubtle,
    fontSize: typography.fontSize.size5,
    lineHeight: "22px",
    fontWeight: typography.fontWeight.medium,
  },
  emptyState: {
    width: "min(560px, 100%)",
    marginTop: "112px",
    marginLeft: "auto",
    marginRight: "auto",
    textAlign: "center",
    ...shorthands.padding(layout.padding.xl),
    ...shorthands.border(
      layout.borderWidth.hairline,
      "solid",
      itinerary.borderPeach18,
    ),
    ...shorthands.borderRadius(layout.radius.xl),
    backgroundColor: itinerary.surfaceCardSoft,
    boxShadow: itineraryShadows.emptyState,
  },
  emptyTitle: {
    color: itinerary.textDark,
    fontSize: typography.fontSize.size9,
    lineHeight: "28px",
    fontWeight: 900,
    marginBottom: layout.spacing[2],
  },
  emptyMessage: {
    color: itinerary.textSecondary,
    fontSize: typography.fontSize.size4,
    lineHeight: "22px",
    fontWeight: typography.fontWeight.medium,
  },
  headerActions: {
    display: "flex",
    gap: layout.spacing[2.5],
    flexWrap: "wrap",
  },
  button: {
    height: layout.controlSize.xs,
    minWidth: "76px",
    ...shorthands.borderRadius(layout.radius.pill),
    textTransform: "none",
    fontSize: typography.fontSize.size1,
    fontWeight: 850,
    boxShadow: "none",
    transitionProperty: "transform, box-shadow, background",
    transitionDuration: layout.duration.normal,
    ...shorthands.padding("0", "14px"),
    ":hover": {
      transform: "translateY(-1px)",
    },
    "& .MuiButton-startIcon": {
      marginRight: layout.spacing[1.5],
      marginLeft: 0,
    },
    "& .MuiButton-startIcon > svg": {
      fontSize: typography.fontSize.size4,
    },
  },
  ghostButton: {
    color: warm.textSecondary,
    backgroundColor: itinerary.bgGhost,
    ...shorthands.border(layout.borderWidth.hairline, "solid", warm.border),
    boxShadow: warmShadows.xs,
    ":hover": {
      color: warm.textPrimary,
      backgroundColor: colors.white,
      boxShadow: itineraryShadows.ghostHover,
    },
  },
  primaryButton: {
    minWidth: "88px",
    color: colors.white,
    background: warmGradients.primary,
    boxShadow: itineraryShadows.primary,
    ":hover": {
      background: warmGradients.primaryHover,
      boxShadow: itineraryShadows.primaryHover,
    },
  },
  dayTabs: {
    display: "flex",
    gap: layout.gap.sm,
    marginBottom: layout.spacing[7],
    overflowX: "auto",
    paddingBottom: layout.spacing[1],
  },
  dayTab: {
    width: "112px",
    height: "62px",
    flexShrink: 0,
    ...shorthands.borderRadius(layout.radius.pill),
    ...shorthands.border(
      layout.borderWidth.hairline,
      "solid",
      itinerary.borderPeach20,
    ),
    backgroundColor: itinerary.surfaceCardSoftest,
    color: itinerary.textSecondary,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    fontWeight: 900,
    fontSize: typography.fontSize.size3,
    lineHeight: "18px",
    boxShadow: itineraryShadows.dayTab,
    transitionProperty: "transform, box-shadow, background, color",
    transitionDuration: layout.duration.normal,
    ":hover": {
      transform: "translateY(-1px)",
      boxShadow: itineraryShadows.dayTabHover,
    },
  },
  dayTabActive: {
    background: itineraryGradients.coral,
    color: `${colors.white} !important`,
    ...shorthands.borderColor(colors.transparent),
    boxShadow: itineraryShadows.dayTabActive,
  },
  dayDate: {
    fontSize: typography.fontSize.size0,
    lineHeight: "14px",
    fontWeight: 800,
    color: "inherit",
  },
  sectionBar: {
    minHeight: "72px",
    ...shorthands.border(
      layout.borderWidth.hairline,
      "solid",
      itinerary.borderPeach16,
    ),
    ...shorthands.borderRadius(layout.radius.xl),
    backgroundColor: itinerary.surfaceCardSofter,
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: layout.gap.md,
    ...shorthands.padding(
      layout.spacing[3.5],
      layout.spacing[4.5],
      layout.spacing[3.5],
      "22px",
    ),
    marginBottom: layout.spacing[5.5],
    boxShadow: itineraryShadows.sectionBar,
    "@media (max-width: 680px)": {
      alignItems: "flex-start",
      flexDirection: "column",
    },
  },
  sectionTitle: {
    color: itinerary.textDark,
    fontSize: typography.fontSize.size8,
    lineHeight: "24px",
    fontWeight: 900,
  },
  sectionActions: {
    display: "flex",
    gap: layout.spacing[2.5],
    flexWrap: "wrap",
  },
  compactButton: {
    height: layout.controlSize.md,
    ...shorthands.borderRadius(layout.radius.pill),
    textTransform: "none",
    fontSize: typography.fontSize.size2,
    fontWeight: 850,
    boxShadow: "none",
    ...shorthands.padding("0", layout.padding.md),
  },
  outlineBlueButton: {
    color: warm.coralBright,
    backgroundColor: colors.white,
    ...shorthands.border(
      layout.borderWidth.hairline,
      "solid",
      itinerary.borderCoralStrong,
    ),
    ":hover": {
      backgroundColor: itinerary.bgHoverPeach,
      boxShadow: itineraryShadows.outlineHover,
    },
  },
  regenerateIcon: { color: itinerary.peach },
  timeline: {
    position: "relative",
    paddingLeft: "58px",
    "@media (max-width: 560px)": {
      paddingLeft: "42px",
    },
  },
  connector: {
    position: "absolute",
    left: layout.spacing[6],
    top: "0",
    bottom: "0",
    width: "2px",
    background: itineraryGradients.connector,
    opacity: 0.9,
    "@media (max-width: 560px)": {
      left: layout.spacing[4.5],
    },
  },
  activityRow: {
    position: "relative",
    marginBottom: layout.spacing[4.5],
  },
  marker: {
    position: "absolute",
    left: "-58px",
    top: "5px",
    width: layout.controlSize.xl,
    height: layout.controlSize.xl,
    ...shorthands.borderRadius(layout.radius.lg),
    backgroundColor: itinerary.bgGradientMid,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    boxShadow: itineraryShadows.marker,
    "@media (max-width: 560px)": {
      left: "-42px",
      width: layout.controlSize.xs,
      height: layout.controlSize.xs,
      ...shorthands.borderRadius("13px"),
    },
  },
  markerIcon: {
    fontSize: typography.fontSize.size9,
    "@media (max-width: 560px)": {
      fontSize: typography.fontSize.size7,
    },
  },
  markerGreen: {
    color: itinerary.markerGreen,
    ...shorthands.border(
      layout.borderWidth.hairline,
      "solid",
      itinerary.markerBorderGreen,
    ),
  },
  markerPurple: {
    color: itinerary.peach,
    ...shorthands.border(
      layout.borderWidth.hairline,
      "solid",
      itinerary.markerBorderPeach,
    ),
  },
  markerBlue: {
    color: itinerary.pink,
    ...shorthands.border(
      layout.borderWidth.hairline,
      "solid",
      itinerary.markerBorderPink,
    ),
  },
  markerCyan: {
    color: warm.coralBright,
    ...shorthands.border(
      layout.borderWidth.hairline,
      "solid",
      itinerary.markerBorderCoral,
    ),
  },
  markerOrange: {
    color: itinerary.peach,
    ...shorthands.border(
      layout.borderWidth.hairline,
      "solid",
      itinerary.markerBorderOrange,
    ),
  },
  markerRed: {
    color: itinerary.clay,
    ...shorthands.border(
      layout.borderWidth.hairline,
      "solid",
      itinerary.markerBorderClay,
    ),
  },
  activityCard: {
    minHeight: "142px",
    ...shorthands.border(
      layout.borderWidth.hairline,
      "solid",
      itinerary.borderPeach16,
    ),
    ...shorthands.borderRadius("26px"),
    backgroundColor: itinerary.surfaceCard,
    boxShadow: itineraryShadows.activityCard,
    display: "flex",
    justifyContent: "space-between",
    gap: layout.spacing[5],
    ...shorthands.padding(
      layout.spacing[5.5],
      layout.spacing[5.5],
      layout.spacing[5],
      layout.padding.lg,
    ),
    transitionProperty: "transform, box-shadow",
    transitionDuration: layout.duration.normal,
    ":hover": {
      transform: "translateY(-2px)",
      boxShadow: itineraryShadows.activityCardHover,
    },
    "@media (max-width: 620px)": {
      flexDirection: "column",
      ...shorthands.padding("18px"),
    },
  },
  activityContent: {
    minWidth: 0,
  },
  activityMeta: {
    display: "flex",
    alignItems: "center",
    gap: "9px",
    flexWrap: "wrap",
    marginBottom: "9px",
  },
  category: {
    height: layout.spacing[5.5],
    display: "inline-flex",
    alignItems: "center",
    ...shorthands.padding("0", "10px"),
    ...shorthands.borderRadius(layout.radius.pill),
    backgroundColor: itinerary.bgBadge,
    color: warm.coralBright,
    fontSize: typography.fontSize.size0,
    lineHeight: "14px",
    fontWeight: 900,
    textTransform: "uppercase",
  },
  categoryBlue: {
    backgroundColor: itinerary.categoryPinkBg,
    color: itinerary.pink,
  },
  categoryGreen: {
    backgroundColor: itinerary.categoryGreenBg,
    color: itinerary.categoryGreenText,
  },
  categoryAmber: {
    backgroundColor: itinerary.categoryAmberBg,
    color: itinerary.peach,
  },
  categoryOrange: {
    backgroundColor: itinerary.categoryAmberBg,
    color: itinerary.peach,
  },
  categoryRed: {
    backgroundColor: itinerary.categoryRedBg,
    color: warm.coralBright,
  },
  activityTime: {
    color: itinerary.textTertiary,
    fontSize: typography.fontSize.size2,
    lineHeight: "17px",
    fontWeight: 750,
  },
  activityTitle: {
    color: itinerary.textDarkest,
    fontSize: typography.fontSize.size8,
    lineHeight: "25px",
    fontWeight: 900,
    marginBottom: layout.spacing[3],
  },
  activityDescription: {
    color: itinerary.textBody,
    fontSize: typography.fontSize.size4,
    lineHeight: "22px",
    fontWeight: 450,
    marginBottom: layout.spacing[4],
  },
  detailLine: {
    display: "flex",
    alignItems: "center",
    gap: layout.gap.md,
    flexWrap: "wrap",
    color: itinerary.textMuted,
    fontSize: typography.fontSize.size2,
    lineHeight: "17px",
  },
  detailItem: {
    display: "inline-flex",
    alignItems: "center",
    gap: layout.spacing[1.5],
    whiteSpace: "nowrap",
  },
  detailIcon: { color: itinerary.pink, fontSize: typography.fontSize.size5 },
  trainIcon: { color: itinerary.peach, fontSize: typography.fontSize.size5 },
  mutedIcon: {
    color: itinerary.textDisabled,
    fontSize: typography.fontSize.size5,
  },
  costIcon: { color: itinerary.peach, fontSize: typography.fontSize.size5 },
  weatherIcon: {
    color: itinerary.textTertiary,
    fontSize: typography.fontSize.size5,
  },
  cardActions: {
    display: "flex",
    gap: layout.gap.xs,
    flexShrink: 0,
    "@media (max-width: 620px)": {
      alignSelf: "flex-end",
    },
  },
  iconButton: {
    width: layout.controlSize.xs,
    height: layout.controlSize.xs,
    ...shorthands.border(
      layout.borderWidth.hairline,
      "solid",
      itinerary.borderPeach20,
    ),
    ...shorthands.borderRadius(layout.radius.md),
    backgroundColor: colors.white,
    boxShadow: itineraryShadows.iconButton,
    ":hover": {
      backgroundColor: itinerary.bgHoverCream,
    },
  },
  editIcon: { color: itinerary.peach, fontSize: typography.fontSize.size7 },
  calendarIcon: { color: itinerary.pink, fontSize: typography.fontSize.size7 },
  deleteIcon: {
    color: itinerary.textDisabled,
    fontSize: typography.fontSize.size7,
  },
});
