"""updatet users table

Revision ID: 04d6ba844262
Revises: 2d3e05a03003
Create Date: 2026-08-10 20:35:26.179826

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "04d6ba844262"
down_revision: str | Sequence[str] | None = "2d3e05a03003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
