"""add user and trip to conversations

Revision ID: 57cec53101b3
Revises: 1460e14c3c2d
Create Date: 2026-08-10 21:54:12.204072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57cec53101b3'
down_revision: Union[str, Sequence[str], None] = '1460e14c3c2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('conversations', sa.Column('trip_id', sa.Integer(), nullable=True))
    op.add_column('conversations', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.create_foreign_key(None, 'conversations', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'conversations', 'trips', ['trip_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_column('conversations', 'updated_at')
    op.drop_column('conversations', 'trip_id')
    op.drop_column('conversations', 'user_id')
    # ### end Alembic commands ###
