"""create trip preference table

Revision ID: 94f61f895079
Revises: 04d6ba844262
Create Date: 2026-08-10 20:51:59.326825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '94f61f895079'
down_revision: Union[str, Sequence[str], None] = '04d6ba844262'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trip_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('travel_style', sa.String(length=100), nullable=True),
    sa.Column('budget_level', sa.String(length=50), nullable=True),
    sa.Column('food_preference', sa.String(length=100), nullable=True),
    sa.Column('accommodation_type', sa.String(length=100), nullable=True),
    sa.Column('transportation_preference', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trip_preferences_id'), 'trip_preferences', ['id'], unique=False)
    op.create_index(op.f('ix_trip_preferences_trip_id'), 'trip_preferences', ['trip_id'], unique=True)
    op.drop_table('messages')
    op.drop_table('conversations')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trip_preferences_trip_id'), table_name='trip_preferences')
    op.drop_index(op.f('ix_trip_preferences_id'), table_name='trip_preferences')
    op.drop_table('trip_preferences')
    # ### end Alembic commands ###
