"""create itineraries days table

Revision ID: ff20b28a4d93
Revises: 69a352f8dec9
Create Date: 2026-08-10 23:26:58.133303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff20b28a4d93'
down_revision: Union[str, Sequence[str], None] = '69a352f8dec9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('itinerary_days',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('itinerary_id', sa.Integer(), nullable=False),
    sa.Column('day_number', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['itinerary_id'], ['itineraries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_itinerary_days_id'), 'itinerary_days', ['id'], unique=False)
    op.create_index(op.f('ix_itinerary_days_itinerary_id'), 'itinerary_days', ['itinerary_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_itinerary_days_itinerary_id'), table_name='itinerary_days')
    op.drop_index(op.f('ix_itinerary_days_id'), table_name='itinerary_days')
    op.drop_table('itinerary_days')
    # ### end Alembic commands ###
