import { makeStyles } from "@griffel/react";
import { fadeUp, pulse } from "../../common/theme/animations";
import { semanticColors, warm } from "../../common/theme/colors";
import {
  layout,
  typography,
  typographyPresets,
} from "../../common/theme/typography";

export const useSplashScreenStyles = makeStyles({
  root: {
    position: "relative",
    display: "flex",
    minHeight: "100dvh",
    width: "100%",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
    backgroundImage: `radial-gradient(circle at 12% 8%, ${semanticColors.bgAccent} 0%, transparent 34%), radial-gradient(circle at 88% 92%, ${semanticColors.bgInteractiveSubtle} 0%, transparent 32%), linear-gradient(160deg, ${semanticColors.bgPage} 0%, ${semanticColors.bgPrimary} 55%, ${warm.bgTint} 100%)`,
    color: warm.textPrimary,
  },
  overlay: {
    position: "absolute",
    inset: 0,
    backgroundImage: `radial-gradient(circle at 50% 42%, color-mix(in srgb, ${semanticColors.bgPrimary} 55%, transparent) 0%, transparent 50%), radial-gradient(circle at 16% 26%, ${semanticColors.bgAccent} 0%, transparent 36%), radial-gradient(circle at 84% 74%, ${semanticColors.bgInteractiveSubtle} 0%, transparent 38%)`,
  },
  content: {
    position: "relative",
    zIndex: 1,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    padding: layout.padding.lg,
    textAlign: "center",
  },
  logoWrapper: {
    width: "clamp(120px, 22vw, 220px)",
    height: "clamp(120px, 22vw, 220px)",
    marginBottom: layout.spacing[8],
    animationName: {
      from: { opacity: 0, transform: "scale(.72)" },
      to: { opacity: 1, transform: "scale(1)" },
    },
    animationDuration: ".9s",
    animationTimingFunction: "cubic-bezier(.22, 1, .36, 1)",
    animationFillMode: "both",
  },
  logo: {
    width: "100%",
    height: "100%",
    objectFit: "contain",
    filter: `drop-shadow(0 18px 36px color-mix(in srgb, ${warm.textPrimary} 22%, transparent))`,
    animationName: { "50%": { transform: "translateY(-8px)" } },
    animationDuration: "6s",
    animationTimingFunction: "ease-in-out",
    animationDelay: ".9s",
    animationIterationCount: "infinite",
  },
  title: {
    ...typographyPresets.brand,
    fontFamily: typography.fontFamily.brand,
    fontSize: "clamp(32px, 4.5vw, 50px)",
    fontWeight: typography.fontWeight.normal,
    color: warm.rose,
    textShadow: `0 2px 12px color-mix(in srgb, ${warm.rose} 30%, transparent)`,
    margin: `0 0 ${layout.spacing[3]}`,
    ...fadeUp,
    animationDelay: ".5s",
  },
  slogan: {
    ...typographyPresets.bodyLarge,
    fontSize: "clamp(15px, 2vw, 21px)",
    fontWeight: typography.fontWeight.medium,
    letterSpacing: typography.letterSpacing.wide,
    color: warm.textSecondary,
    margin: 0,
    ...fadeUp,
    animationDelay: ".75s",
  },
  loadingBar: {
    marginTop: layout.spacing[10],
    ...fadeUp,
    animationDelay: "1.05s",
  },
  pattern: {
    pointerEvents: "none",
    position: "absolute",
    inset: 0,
    overflow: "hidden",
  },
  patternItem: {
    position: "absolute",
    lineHeight: 1,
  },
  loadingBarRoot: {
    position: "relative",
    display: "flex",
    alignItems: "center",
    width: "150px",
    height: "24px",
  },
  startDot: {
    width: "8px",
    height: "8px",
    borderRadius: "50%",
    backgroundColor: warm.coral,
    boxShadow: `0 0 0 3px ${semanticColors.bgAccent}`,
    ...pulse,
  },
  route: {
    flexGrow: 1,
    height: "2px",
    backgroundImage: `repeating-linear-gradient(90deg, color-mix(in srgb, ${warm.textPrimary} 18%, transparent) 0 6px, transparent 6px 12px)`,
  },
  endDot: {
    width: "8px",
    height: "8px",
    borderRadius: "50%",
    backgroundColor: warm.rose,
    boxShadow: `0 0 0 3px ${semanticColors.bgInteractiveSubtle}`,
    ...pulse,
  },
  plane: {
    position: "absolute",
    top: "4px",
    left: "8px",
    width: "16px",
    height: "16px",
    color: warm.coral,
    filter: `drop-shadow(0 1px 3px color-mix(in srgb, ${warm.rose} 30%, transparent))`,
    animationName: {
      "0%, 15%": { transform: "translateX(0) rotate(-12deg)", opacity: 0 },
      "25%, 85%": { opacity: 1 },
      "100%": { transform: "translateX(126px) rotate(-12deg)", opacity: 0 },
    },
    animationDuration: "2.4s",
    animationTimingFunction: "ease-in-out",
    animationIterationCount: "infinite",
  },
});
